### ISSUE TITLE
eg-row

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#1]
@BryanCrotaz I have another type of table which could also be supported by ember grid: a "comparison table" where various funds are columns, and rows are various data-points. This is really transpose of "normal" table.

But even in a "normal" table, I'm thinking that sometimes it might be good to attach (e.g) style information  to rows-- hence perhaps good to support `eg-row` as declarator.

The question would be where to define cells -- in either one or the other is ok. Probably in both is simply an error. Perhaps, though, one could have the following sort of structure:

```
{{#eg-rows}}
  {{#eg-row key="foo"}}...
    ...

{{#eg-columns}}
  {{#eg-column key="bar}}
    {{#eg-body forRow="foo"}}
      ...
   {{/eg-body}}
    {{#eg-body forRow="other-row"}}
      ...
   {{/eg-body}}
   
```
which would give alternate body cell definitions depending on row for given column. (?)

**Comment by BryanCrotaz** [comment]
In order to do alternating colours, we need to pass index to the body
cell block.
