### ISSUE TITLE
readme is confusing in Control Scrolling

### ISSUE THREAD

**Issue by BryanCrotaz** [shaunc/ember-grid#12]
> If either width and scroll-y are both not specified, or if height and scroll-x are both not specified, then ember-grid sets scrolling to false displays all columns or rows (respectively).

I'm not sure what you're trying to say here.

Also needs an example if you're saying these are properties on ember-grid

**Comment by shaunc** [comment]
Fixed & expanded -- reopen if you think it still isn't right.
