### ISSUE TITLE
ember-cli-csp-style ... great! but...

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#13]
@BryanCrotaz  -- ember-cli-csp-style looks great! ... however, I'm getting 

 > Uncaught Error: Could not find module `ember-cli-csp-style/mixins/csp-style` imported from `ember-grid/eg-render/eg-header/component`

when I try to run. Do I have to do anything besides `ember install ember-cli-csp-style` ?

PS Next April fools, you need to release `ember-cli-gangnam-style` which makes your components jiggle unpredictably.

**Comment by shaunc** [comment]
Pushed merged version but can't use right now pending fix.

**Comment by BryanCrotaz** [comment]
Fixed the package. there was a naming mismatch in it. Upgraded it to 0.1.1
