### ISSUE TITLE
column auto size is broken

### ISSUE THREAD

**Issue by BryanCrotaz** [shaunc/ember-grid#14]
`column.width` is not being set by whatever discovers correct autosize, so columns are different widths in header and body

**Comment by shaunc** [comment]
Hmm... its done here....

    calcContentWidth(width, columnsWithoutWidth) {
      if (width == null) {
        width = this.readElementWidth();
      }
      if (width == null) { return; }
      var colWidth = width / columnsWithoutWidth;
      var columns = this.get('columns');
      var contentWidth = 0;
      columns.forEach((col)=>{
        if(col.width == null) {
          col.set('width', colWidth);
        }
        contentWidth += col.width;
      });
      this.set('contentWidth', contentWidth);
    },
   
It seems to me its working? Perhaps you can send a screenshot? Or it will get picked up by the tests, which I am turning to again now...

**Comment by BryanCrotaz** [comment]
Look at your minimal example in the demo.

**Comment by BryanCrotaz** [comment]
![image](https://cloud.githubusercontent.com/assets/2016523/9446420/873b4506-4a89-11e5-8471-3163431ea168.png)

**Comment by BryanCrotaz** [comment]
As soon as you start to drag a column, that sets the width and that column comes good.

**Comment by shaunc** [comment]
interesting ... not what I see. 

For the moment I'm abandoning ember-cli-mocha as support seems to have dropped off, and am setting up tests in qunit. Hopefully I'll catch it there (starting with overall layout tests), but if not will have to dig in further. (NB I had to reinstall ember-cli to get import from `ember-cli-csp-style` working -- now I've got  1.13.8-master-64d729898b installed. Its possible this could be their bug not ours. :))

**Comment by BryanCrotaz** [comment]
I'm aiming to write some tests in the `ember-cli-csp-style` package. Any thoughts on things that could be improved in it?

**Comment by BryanCrotaz** [comment]
Have you tried going to the demo page?
http://shaunc.github.io/ember-grid/example

What browser/os are you using? I'm using Chrome on Windows (two different machines)

**Comment by shaunc** [comment]
demo pages seems down for the moment. I'm using chrome on mac. Will try to check out in windows later today.

#### ember-cli-csp-style:

I think its great already ... some ideas for the future:

* setting styles with more complex content (e.g. `transition`, or `calc( ... )`)
* setting styles in sub-element (but how to select -- do you want to avoid jquery?)

**Comment by BryanCrotaz** [comment]
commit of 27th doesn't fix initial width in my browser

**Comment by BryanCrotaz** [comment]
overview demo works but minimal doesn't
