### ISSUE TITLE
properly scroll x+y

### ISSUE THREAD

**Issue by BryanCrotaz** [shaunc/ember-grid#27]
x-scroll has to scroll header, body and footer
y-scroll must remain visible

So we must scroll the content of the row but the row must continue to fill parent width.

@shaunc I've added a branch, `remove_ember-collection` where I've implemented the scrolling. We now need to put the virtual row rendering in.

**Comment by shaunc** [comment]
I'm working on redoing scrolling so will take a look at the branch. I'm not sure what your comment means though: on y-scroll we must scroll all of body, header & footer. On x-scroll just scroll within body but width is relative to whole container.

**Comment by BryanCrotaz** [comment]
I've done it the other way around - header and footer should always be displayed, so y only scrolls body. x scrolls header, body and footer

**Comment by shaunc** [comment]
Ach -- sorry my comment evinced cartesian coordinate dyslexia -- what you say is the only sensible thing. ...
