### ISSUE TITLE
scroll columns broken

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#28]
Scroll-columns demo doesn't have x-scroll working. Also `.display` container doesn't have x-scroll enabled.

**Comment by BryanCrotaz** [comment]
Have you pulled my latest fixes?

.display container shouldn't have scroll enabled - see the `scroll-container` and `scroller` pair underneath it

**Comment by BryanCrotaz** [comment]
confirmed it works on my latest commit

**Comment by BryanCrotaz** [comment]
Which browser are you using?

**Comment by shaunc** [comment]
scroll-container for me has dimensions 400x0

chrome

**Comment by shaunc** [comment]
(on mac)

**Comment by BryanCrotaz** [comment]
I get this:
![image](https://cloud.githubusercontent.com/assets/2016523/9839735/38f336e6-5a7a-11e5-914c-d803afa65ff6.png)

**Comment by shaunc** [comment]
I see this in chrome:
![image](https://cloud.githubusercontent.com/assets/193170/9839740/74e73028-5a50-11e5-848c-c5279ababbb8.png)

**Comment by BryanCrotaz** [comment]
see if you can identify where it's going wrong - almost certainly the sizing code you wrote in `ember-grid` - the css I've moved to auto sizes everything except body height. I'm using table rendering to get the body filling the space between header and footer

**Comment by shaunc** [comment]
In firefox:

![image](https://cloud.githubusercontent.com/assets/193170/9839750/8ae9eff0-5a50-11e5-97e7-cfe6b304ffa0.png)

**Comment by BryanCrotaz** [comment]
in windows firefox I get a completely empty DOM

**Comment by BryanCrotaz** [comment]
does the column scroller appear in the DOM but not on screen?

**Comment by shaunc** [comment]
confirm column scroller is in DOM but has 0 height

In safari looks like chrome

**Comment by shaunc** [comment]
problem might be this: on mac scroll-bar is rendered only "if needed" 

y-scrolling is working for me

**Comment by BryanCrotaz** [comment]
interesting - you should get a height of the scrollbar - trace into `getScrollbarHeight` in `eg-render/column-scroller/control`

**Comment by shaunc** [comment]
firefox issues aren't confined to scroll demo -- all tables look like that. Does firefox work for you?

**Comment by BryanCrotaz** [comment]
scrollbar is definitely needed. firefox completely broken for me - html body tag is empty

**Comment by BryanCrotaz** [comment]
"scroll-bar is rendered only "if needed" - that's what `scroll: auto` means. it's deliberate.

**Comment by shaunc** [comment]
what I mean is that on mac scrollbar rendered on top of other content -- and only appears when content is dragged.

Traced in -- your test gives scrollbar height 0

**Comment by BryanCrotaz** [comment]
maybe `getScrollbarHeight` isn't successfully rendering a scrollbar on Mac. Try tracing it and viewing the DOM as it runs

**Comment by shaunc** [comment]
yes ... I think we also need to simulate a drag (if possible?) on a mac

**Comment by shaunc** [comment]
ok ... well since I have a mac in front of me I'll see what I can do

**Comment by shaunc** [comment]
the other issue though is that scrollbar should have 0 height on mac

**Comment by shaunc** [comment]
should only appear if content dragged - so we need to trigger the scroller area accordingly

**Comment by BryanCrotaz** [comment]
Try this technique
http://stackoverflow.com/questions/7855590/how-can-i-prevent-scroll-bars-from-being-hidden-for-os-x-trackpad-users-in-webki

**Comment by shaunc** [comment]
ok ... (being called to dinner -- back in 30 min --- will work on this.) Can you check out what is happening in firefox?

**Comment by BryanCrotaz** [comment]
not a clue - I don't get anything - just an empty body tag. Looks like ember isn't starting up properly

**Comment by BryanCrotaz** [comment]
I'm off to bed - I'll have to leave the Mac rendering issues with you. Probably phones will have same problems

**Comment by BryanCrotaz** [comment]
The more serious bug is that the first column doesn't render correctly in overview demo. Only the first 16 rows render.

**Comment by BryanCrotaz** [comment]
That's the only bug I can see on Windows apart from the slow re-render.

**Comment by shaunc** [comment]
hmm... I'd like put in an option on scroll --- something like:

    scroll-mode=native/always-visible/drag-only

where always-visible is "windows way", and drag-only is "mac way" 

Sleep well! -- will post later on

**Comment by shaunc** [comment]
(first column render -- will look at once I complete lazy render merge as is probably related.)

**Comment by shaunc** [comment]
Now will use native scrolling iff detected height of scrollbar is 0. Re-open if you want some other solution....
