### ISSUE TITLE
mutable is optional in future

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#29]
@BryanCrotaz, @andrewpye ---

To be forward-compatible with angle-brackets, code like this should be avoided:

  	var height = this.attrs.height;
  	// deal with mutable
  	if (height && height.value !== undefined) {
	    height = height.value;
	  }

The problem is that with angle brackets mutable wrapper won't be used.

Better so (and more succinct even in the present):

    var height = this.getAttr('height');

`getAttr` deals with unwrapping mutable -- it also checks if it is really a mutable and not just an object that has "value" attribute.

I'll change it when I encounter it but please use `getAttr` going forward. That also why I wrote code like:

    for (let key in this.attrs) {
      body[key] = this.getAttr(key);
    }

rather than just extending/merging `this.attrs`

**Comment by BryanCrotaz** [comment]
agreed
