### ISSUE TITLE
es6 style vs bind

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#30]
@BryanCrotaz --

What do you think about using es6 ()=> rather than bind? Ie instead of

    Ember.run.later(function() {
      ...
    }.bind(this));

writing:

    Ember.run.later(()=>{
      ...
    });

**Comment by lcpriest** [comment]
Is this fundamentally the same thing? If so, the second one is preferable.

**Comment by BryanCrotaz** [comment]
I agree, second is preferable

**Comment by shaunc** [comment]
very good.
