### ISSUE TITLE
Initial dummy app fails

### ISSUE THREAD

**Issue by lcpriest** [shaunc/ember-grid#33]
After cloning the repo and running 
```
npm install
bower install
ember serve
```

A build error is thrown:
```
ENOTDIR, not a directory '/Users/lcp/Development/Ember/ember-grid/tmp/broccoli_merge_trees-input_base_path-CYkD6edB.tmp/1/'
Error: ENOTDIR, not a directory '/Users/lcp/Development/Ember/ember-grid/tmp/broccoli_merge_trees-input_base_path-CYkD6edB.tmp/1/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at /Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:35:19
    at Array.map (native)
    at mergeRelativePath (/Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:33:28)
    at BroccoliMergeTrees.build (/Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:3)
    at /Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/lcp/Development/Ember/ember-grid/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
```

It sounds like it may be something similar to this:
http://www.tech.shinynewthings.com/?p=311

But there must be another solution or it would be failing for everyone.

**Comment by shaunc** [comment]
If you add style.scss does it work for you? I checked out a clean copy and rebuilt just yesterday, so this isn't a problem on all platforms, I think. What version of ember-cli do you have installed? I have:

    $ ember version
    version: 1.13.8
    node: 0.12.4
    npm: 2.13.4
    os: darwin x64

**Comment by BryanCrotaz** [comment]
I'm seeing the same problem tonight. Tried cleaning caches and reinstalling but same problem.

https://github.com/broccolijs/broccoli-merge-trees/issues/23

**Comment by lcpriest** [comment]
Globally I am on the same ember as you @shaunc 
```
{6:26}[2.2.2]~ ➭ ember -v
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64
```

**Comment by lcpriest** [comment]
Is that one style.scss per pod?

**Comment by shaunc** [comment]
@lcpriest -- I just took the style.scss idea from the report you provided.

My only guess is that *something* has gone to a new version in npm. Could actually be broccoli but maybe something else. In the "npm-list" branch, I have added npm-list.txt, which I produced by: `npm list > npm-list.txt`. You might want to pull that branch then dump your local manifest and compare.

In the best case we'll just have to move up the version of something else in package.json to restore compatibility.

I'm also trying a clean install and will know soon if I get it too on new fresh install.

**Comment by lcpriest** [comment]
```
@@ -442,7 +442,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ │       └── path-is-absolute@1.0.0
 │ ├─┬ broccoli-sane-watcher@1.1.4
 │ │ └── broccoli-slow-trees@1.1.0
-│ ├─┬ broccoli-sourcemap-concat@1.1.2
+│ ├─┬ broccoli-sourcemap-concat@1.1.3
 │ │ ├─┬ broccoli-caching-writer@2.0.1
 │ │ │ ├─┬ broccoli-plugin@1.1.0
 │ │ │ │ ├─┬ quick-temp@0.1.3
@@ -458,7 +458,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ │ │ │     │ └── wrappy@1.0.1
 │ │ │ │     └── path-is-absolute@1.0.0
 │ │ │ ├── lodash-node@3.10.1
-│ │ │ └── walk-sync@0.2.0
+│ │ │ └── walk-sync@0.2.1
 │ │ ├─┬ fast-sourcemap-concat@0.2.5
 │ │ │ ├─┬ chalk@0.5.1
 │ │ │ │ ├── ansi-styles@1.1.0
@@ -684,7 +684,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ │ │ └── sprintf-js@1.0.3
 │ │ ├── entities@1.1.1
 │ │ ├── linkify-it@1.2.0
-│ │ ├── mdurl@1.0.0
+│ │ ├── mdurl@1.0.1
 │ │ └── uc.micro@1.0.0
 │ ├─┬ markdown-it-terminal@0.0.2
 │ │ ├── ansi-styles@2.1.0
@@ -1505,7 +1505,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ │ │ ├── mime@1.3.4
 │ │ │ ├─┬ promise@6.1.0
 │ │ │ │ └── asap@1.0.0
-│ │ │ ├─┬ request@2.61.0
+│ │ │ ├─┬ request@2.62.0
 │ │ │ │ ├── aws-sign2@0.5.0
 │ │ │ │ ├─┬ bl@1.0.0
 │ │ │ │ │ └─┬ readable-stream@2.0.2
@@ -1555,7 +1555,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ │ │ │ │ └── mime-db@1.18.0
 │ │ │ │ ├── node-uuid@1.4.3
 │ │ │ │ ├── oauth-sign@0.8.0
-│ │ │ │ ├── qs@4.0.0
+│ │ │ │ ├── qs@5.1.0
 │ │ │ │ ├── stringstream@0.0.4
 │ │ │ │ ├── tough-cookie@2.0.0
 │ │ │ │ └── tunnel-agent@0.4.1
@@ -1846,7 +1846,7 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │   │   └── wordwrap@0.0.2
 │   └── walk-sync@0.1.3
 ├─┬ ember-collection@0.0.0 (git://github.com/shaunc/ember-collection.git#49cdcc86c9227615a72a86edcf81b630ad6f2ba6)
-│ └── layout-bin-packer@1.0.5
+│ └── layout-bin-packer@1.2.0
 ├─┬ ember-disable-prototype-extensions@1.0.1
 │ └─┬ ember-cli-babel@4.3.3
 │   ├─┬ broccoli-babel-transpiler@4.1.0
@@ -1991,4 +1991,3 @@ ember-grid@0.1.0 /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid
 │ ├── rsvp@3.1.0
 │ └── sync-exec@0.5.0
 └── es5-shim@4.1.13
```

That's the diff of our two files

**Comment by shaunc** [comment]
ok ... this was a pain ... but please try latest master. I was able to reproduce, but simply swapping node_modules pieces successively didn't work exactly. I think the problem may have been differing versions of broccoli-funnel in the dependency tree. In fact, broccoli-funnel was only in master because I was trying to include polyfills to allow us to use `requestAnimationFrame` with phantomjs. Now that we have dropped ember-collection, no need. I also updated to newer version of ember-cli-babel, which was implicated. Perhaps some of these packages should be listing broccoli-funnel as a peer dependency to insure harmony.

However -- (at least right now while London sleeps :)) I was able to download a clean version and build dependencies. If you can give it a whirl and report back I would be obliged.

**Comment by lcpriest** [comment]
Can confirm that that works. Nice!

**Comment by lcpriest** [comment]
I'll look at some of the other issues after work (I'm on GMT+8). I currently am not using this in our projects, but will be testing the waters for a few weeks and then try implement it in one of our apps.

**Comment by shaunc** [comment]
Great -- thanks! Our goal is to make the internals more robust and get the test suite in shape. I wouldn't recommend it for production now in any case, but glad to have you kicking the tires, and hope to get to production-ready soon. We'll try to be responsive to any issues (though its not yet going to be a priority to add features). I have a lot of other work, but am spending time whenever I can. Bryan is quite energetic himself.

**Comment by lcpriest** [comment]
I shouldn't have too many issues, I'll open pull requests if I have changes or fixes. This was just weird and I didn't have a working version to diff off of.
