### ISSUE TITLE
Use of "_" for properties

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#9]
It was hard for me to discern what principle we were using to mark properties with leading underscore. Did you have something in mind?

**Comment by BryanCrotaz** [comment]
underscore was for private methods and properties.It needs a review

**Comment by shaunc** [comment]
In the past, when parameters and internal state were mashed together, a reasonable best practice was to put "_" on all non-parameter attributes. Now with `attrs` hash separate from other properties, as well as DDAU style & explicit listener functions that which make it more problematic to interact directly with child component shape, it seems that properties & methods are already pretty isolated from component users.

It would seem to me, then, that we might want to reserve "_" for methods & properties that are really private from other parts of the addon, not just from the user -- sort of a "don't touch me until you've read the code and understand what you are doing" mark that can be useful especially for elements whose state might not be exactly coupled to application state. (E.g. a method which will trigger an error if certain other properties aren't set a particular way).

In objects that travel across the addon boundary to the user, "_" to mark private is good: thus `_zones` is good. But uses such as `_requiredPresent` just makes the code look slightly uglier, and we should take out.

How does that sound?

**Comment by BryanCrotaz** [comment]
Sounds good - _ should be reserved for truly private - only the component's own template may use it

**Comment by shaunc** [comment]
We may have gotten ahead of ourselves here.

https://github.com/emberjs/ember.js/issues/12196

I'm having trouble in testing with `columns` attribute shadowing computed columns in `ember-grid` after `didReceiveAttrs`. Do you know if "being an angle-bracket component" simply a matter of how the user happens to invoke the component, or is there something we can do to mark our components as angle-bracket components? 

To get first tests working, I may change property `columns` back to `_columns` in ember grid, at least. The problem may be limited to cases where you actually want to replace external attribute with internal.

**Comment by shaunc** [comment]
@rjblue confirmed that shadowing will be with us for a while -- so if property is different than attribute we do have to insure name changes. "_" is ok in this case. However, we still don't need "_" to signal to user, as properties are fairly inaccessible.
